config/routes.rb
OcgBackend::Application.routes.draw do

  devise_for :users
  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
    get "sign_up", to: "devise/registrations#new"
    get "sign_out", to: "devise/sessions#destroy", as: "signout"
  end

  root 'regions#index'

  resources :regions do
    resources :rocks, only: [:new, :create]
  end

  resources :rocks, except: [:new, :create] do
    resources :routes, only: [:new, :create]
  end

  resources :routes, except: [:new, :create]

  

end

app/models/route.rb
class Route < ActiveRecord::Base
  belongs_to :rock
  validates :rock, presence: true

  acts_as_taggable_on :material
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]
  before_action :set_rock, only: [:new, :create]

  # GET /routes
  # GET /routes.json
  def index
    @routes = Route.all
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)
    @route.rock = @rock

    respond_to do |format|
      if @route.save
        format.html { redirect_to @route, notice: 'Route was successfully created.' }
        format.json { render action: 'show', status: :created, location: @route }
      else
        format.html { render action: 'new' }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    def set_rock
      @rock = Rock.find(params[:rock_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:name, :difficulty, :description, :rock_id, :material_list)
    end
end

app/helpers/routes_helper.rb
module RoutesHelper
  def breadcrumbs_for_route(route)
    str = "<ol class=\"breadcrumb\">"
    if !route.rock.nil?
      str += breadcrumb_recursion(route.rock.region)
      str += "<li>#{link_to route.rock.name, route.rock}</li>"
    end
    str += "<li class=\"active\">#{route.name}</li>"
    str += "</ol>"
    str
  end
end

app/views/routes/_form.html.erb
<%= form_for([@rock, @route]) do |f| %>
  <% if @route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% @route.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :difficulty %><br>
    <%= f.number_field :difficulty %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :rock_id %><br>
    <%= f.number_field :rock_id %>
  </div>
  <div class="field">
    <%= f.label :material_list %>
    <%= f.text_field :material_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1>Editing route</h1>

<%= render 'form' %>

<%= link_to 'Show', @route %>

app/views/routes/index.html.erb
<h1>Listing routes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Difficulty</th>
      <th>Description</th>
      <th>Rock</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= route.name %></td>
        <td><%= route.difficulty %></td>
        <td><%= route.description %></td>
        <td><%= route.rock_id %></td>
        <td><%= link_to 'Show', route %></td>
        <td><%= link_to 'Edit', edit_route_path(route) %></td>
        <td><%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Route', new_route_path %>

app/views/routes/new.html.erb
<h1>New route</h1>

<%= render 'form' %>

<%= link_to 'Back', rock_path(@route.rock) %>

app/views/routes/show.html.erb
<%= raw breadcrumbs_for_route(@route) %>

<div class="header">
  <h1><%= @route.name %></h1>
</div>

<p>
  <strong><%= t('.difficulty') %>:</strong>
  <%= @route.difficulty %>
</p>

<p>
  <strong><%= t('.description') %>:</strong>
  <%= @route.description %>
</p>

<% @route.material.any? do %>
  <p>
    <strong><%= t('.material') %>:</strong>
    <% @route.material.each do |tag| %>
      <span class="tag"><%= tag.name %></span>
    <% end %>
  </p>
<% end %>

<div class="btn-group">
  <%= link_to t('edit'), edit_route_path(@route), :class => "button" %>
</div>