config/routes.rb
OcgBackend::Application.routes.draw do

  devise_for :users
  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
    get "sign_up", to: "devise/registrations#new"
    get "sign_out", to: "devise/sessions#destroy", as: "signout"
  end

  root 'regions#index'

  resources :regions do
    resources :rocks, only: [:new, :create]
  end

  resources :rocks, except: [:new, :create] do
    resources :routes, only: [:new, :create]
  end

  resources :routes, except: [:new, :create]

  

end

app/models/region.rb
class TreeValidator < ActiveModel::Validator
  def validate(record)
    if record.parent_region == record
      record.errors[:base] << I18n.t('invalid_parent')
    end
    if !record.parent_region.nil? && record.parent_region.rocks.count > 0
      record.errors[:base] << I18n.t('leaf_parent')
    end
    record.child_regions.each do |child|
      if child == record
        record.errors[:base] << I18n.t('invalid_child')
      end
    end
  end
end


class Region < ActiveRecord::Base
  belongs_to :parent_region, class_name: 'Region', inverse_of: :child_regions
  has_many :child_regions, class_name: 'Region',
    inverse_of: :parent_region, foreign_key: :parent_region_id
  has_many :rocks

  validates_with TreeValidator

  scope :top_level, -> { where(parent_region_id: nil) }
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: [:show, :edit, :update, :destroy]

  # GET /regions
  # GET /regions.json
  def index
    @regions = Region.top_level
  end

  # GET /regions/1
  # GET /regions/1.json
  def show
  end

  # GET /regions/new
  def new
    @region = Region.new
  end

  # GET /regions/1/edit
  def edit
  end

  # POST /regions
  # POST /regions.json
  def create
    @region = Region.new(region_params)

    respond_to do |format|
      if @region.save
        format.html { redirect_to @region, notice: 'Region was successfully created.' }
        format.json { render action: 'show', status: :created, location: @region }
      else
        format.html { render action: 'new' }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regions/1
  # PATCH/PUT /regions/1.json
  def update
    respond_to do |format|
      if @region.update(region_params)
        format.html { redirect_to @region, notice: 'Region was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @region.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regions/1
  # DELETE /regions/1.json
  def destroy
    @region.destroy
    respond_to do |format|
      format.html { redirect_to regions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def region_params
      params.require(:region).permit(:name, :parent_region_id)
    end
end

app/helpers/regions_helper.rb
module RegionsHelper
  def breadcrumbs_for_region(region)
    str = "<ol class=\"breadcrumb\">"
    str += breadcrumb_recursion(region.parent_region) unless region.parent_region.nil?
    str += "<li class=\"active\">#{region.name}</li>"
    str += "</ol>"
    str
  end

end

app/views/regions/_form.html.erb
<%= form_for(@region) do |f| %>
  <% if @region.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@region.errors.count, "error") %> prohibited this region from being saved:</h2>

      <ul>
      <% @region.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :parent_region_id %><br>
    <%= f.number_field :parent_region_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/regions/edit.html.erb
<h1>Editing region</h1>

<%= render 'form' %>

<%= link_to 'Show', @region %> |
<%= link_to 'Back', regions_path %>

app/views/regions/index.html.erb
<div class="header">
  <h1>
    <%= t(:regions) %>
    <small>Regions of the World, where you can find some climbs</small>
  </h1>
</div>

<table class="tbl">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @regions.each do |region| %>
      <tr>
        <td><%= link_to region.name, region %></td>
        <td>
          <div class="btn-group">
            <%= link_to 'Edit', edit_region_path(region),
              :class => "embedded-button" %>
            <%= link_to 'Destroy', region, method: :delete,
              data: { confirm: 'Are you sure?' }, :class => "embedded-button-danger" %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add a Region', new_region_path, :class => "button" %>

app/views/regions/new.html.erb
<h1>New region</h1>

<%= render 'form' %>

<%= link_to 'Back', regions_path %>

app/views/regions/show.html.erb
<%= raw breadcrumbs_for_region(@region) %>

<div class="header">
  <h1><%= @region.name %></h1>
</div>

<% if !@region.child_regions.empty? %>
  <h2>Regions in <%= @region.name %></h2>
  <div class="list-group">
    <% @region.child_regions.each do |child_region| %>
      <%= link_to child_region.name, child_region, :class => "list-group-item" %>
    <% end %>
  </div>
<% end %>

<% if !@region.rocks.empty? %>
<h2>Rocks in <%= @region.name %></h2>
<div class="list-group">
  <% @region.rocks.each do |rock| %>
    <%= link_to rock.name, rock, :class => "list-group-item" %>
  <% end %>
</div>
<% end %>

<div class="btn-group">
  <%= link_to 'Add a Region', new_region_path, :class => "button" %>
  <%= link_to 'Edit this Region', edit_region_path(@region), :class => "button" %>
</div>