config/routes.rb
OcgBackend::Application.routes.draw do

  devise_for :users
  devise_scope :user do
    get "sign_in", to: "devise/sessions#new"
    get "sign_up", to: "devise/registrations#new"
    get "sign_out", to: "devise/sessions#destroy", as: "signout"
  end

  root 'regions#index'

  resources :regions do
    resources :rocks, only: [:new, :create]
  end

  resources :rocks, except: [:new, :create] do
    resources :routes, only: [:new, :create]
  end

  resources :routes, except: [:new, :create]

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Open Climbing Guide</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navigation" role="navigation">
    <div class=navigation-header">
      <button type="button" class="navigation-toggle" data-toggle="collapse"
        data-target="main-navigation">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Open Climbing Guide", root_path, :class => "brand" %>
    </div>

    <div class="navigation-main" id="main-navigation">
      <ul class="navigation-list">
        <li><%= link_to t(:regions), regions_path %></li>
      </ul>

      <%= form_tag '#', :class => 'navigation-search-form' do %>
        <input-group>
          <input type="text" placeholder="Find a Rock...">
        </input-group>
        <button type="submit" class="submit-button">Submit</button>
      <% end %>

      <% if user_signed_in? %>
        <ul class="navigation-right">
          <li><%= link_to "Sign Out", signout_path %></li>
        </ul>
      <% else %>
        <%= form_for(resource, as: resource_name, url: session_path(resource_name),
                 :html => { class: "navigation-login-form" }) do |f| %>
          <input-group>
            <%= f.email_field :email, placeholder: "E-Mail" %>
          </input-group>
          <input-group>
            <%= f.password_field :password, placeholder: "Password", autocomplete: "off" %>
          </input-group>
          <button type="submit" class="submit-button">Sign In</button>
        <% end %>
      <% end %>

      <ul class="navigation-right">
        <li><%= link_to t(:about), '#' %></li>
        <li><%= link_to t(:impress), '#' %></li>
      </ul>
    </div>
  </nav>

  <div class="main-page">
    <% unless notice.nil? %>
      <p id="notice"><%= notice %></p>
    <% end %>
    <% unless alert.nil? %>
      <p id="alert"><%= alert %></p>
    <% end %>

    <%= yield %>
  </div>

</body>
</html>